name: 'Get Latest Commit'
description: 'Fetch info about latest commit made to a branch'
inputs:
  branch-name:
    description: 'Name of the branch'
    required: true
outputs:
  message:
    description: 'Latest commit message'
  sha:
    description: 'Latest commit SHA'
  author:
    description: 'Latest commit author'
  committer:
    description: 'Latest commit committer'
runs:
  using: 'node16'
  main: 'dist/index.js'
