name: 'Get Latest Commit'
description: 'Fetch info about latest commit made to a branch'
inputs:
  branch-name:
    description: 'Name of the branch'
    required: true
outputs:
  commit-message:
    description: 'Latest commit message'
  commit-sha:
    description: 'Latest commit SHA'
  commit-author:
    description: 'Latest commit author'
  commit-committer:
    description: 'Latest commit committer'
runs:
  using: 'node16'
  main: 'dist/index.js'
